### ISSUE TITLE
Init State onEntryStateInit() isn't called

### ISSUE THREAD

**Issue by marcoxsurf** [beworker/tinymachine#3]
Hi, 
I've setup my FSM in this way, INIT->REC_SESS<->PAUSE_SESS, REC_SESS->END_SESS->INIT

```
public class TinyHandler {
        // Handlers for INIT
        @StateHandler(stae = INIT, type = Type.OnEntry)
        // This method is called when machine enters INIT
        public void onEntryStateInit() {
            Log.d(TAG, "Entering INIT");
            createSession();
            ...
        }
}
```

The method `onEntryStateInit()` is not called.
To get around this issue, I've setup another State, the `STATE_0` called as a starting state and afterwards `INIT` is called.
 `mTinyMachine = new TinyMachine(new TinyHandler(), STATE_0);
        mTinyMachine.transitionTo(INIT);`
Is this a corret behaviour?

**Comment by beworker** [comment]
This is by design. There is no `OnEntry` event for the initial state. This is done to avoid any state transitions before `TinyMachine`'s constructor is executed. I usually use `STATE_UNDEFINED = -1` for the initial state and then move FSM into the state I need, exactly like you do.

Maybe I could add a well known `STATE_UNDEFINED = Integer.MAX_VALUE` to the API and use it internally without asking for initial state at all.

**Comment by marcoxsurf** [comment]
It would be better with STATE_UNDEFINED = -1 specified in the docs and explained why you need it. 
Then you can leave everything else in place.

**Comment by beworker** [comment]
It is already documented in the constructor of the `TinyMachine` class that the `OnEnter` is not reported for the given initial state.
